zstyle ':completion:*' auto-description 'specify %d'
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' file-sort name
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd directory
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=*'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/daniel/.zshrc'

fpath+=~/.zfunc
autoload -Uz compinit promptinit
compinit
promptinit #; prompt gentoo
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
setopt extendedglob
unsetopt autocd beep
bindkey -v
[[ $- = *i* ]] && source ~/liquidprompt/liquidprompt
source ~/.aliases

export EDITOR='vim'
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export PATH=$PATH:$HOME/.scripts:/opt
#. spack/share/spack/setup-env.sh
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /usr/share/zsh/plugins/zsh-autopair/autopair.zsh
fortune computers -s | cowsay -f `shuf -n 1 $HOME/.cows`
#zsh ~/scripts/pokemon.sh
#eval "$(starship init zsh)"
source ~/.zplug/init.zsh
zplug "dracula/zsh",as:theme
ZSH_THEME="dracula"
